(use compat.sicp)

(define (make-account balance password)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                   balance)
            "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
    (define (incorrect-password amount) false)
    (define (dispatch p m)
        (if (eq? p password)
            (cond ((eq? m 'withdraw) withdraw)
                  ((eq? m 'deposit) deposit)
                  ((eq? m 'check-password) true)
                  (else (error "Unknown request -- MAKE-ACCOUNT" m)))
            incorrect-password))
    dispatch)

(define (make-joint acc password joint-password)
    (if (acc password 'check-password)
        (lambda (p m)
            (if (eq? p joint-password)
                (acc password m)
                (error "Incorrect password")))
        (error "Incorrect password")))

(define peter-acc (make-account 100 'open-sesame))
(define paul-acc (make-joint peter-acc 'open-sesame 'rosebud))

(print ((paul-acc 'rosebud 'withdraw) 40))
(print ((peter-acc 'open-sesame 'withdraw) 10))
